main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index

trailer:
  method: 'get'
  path: 'trailer'
  controller: App\Controller\HomeController
  action: trailer

login_page:
  method: 'get'
  path: 'login'
  controller: App\Controller\UsersController
  action: index

login_action:
  method: 'post'
  path: 'login'
  controller: App\Controller\UsersController
  action: login

logout:
  method: 'get'
  path: 'logout'
  controller: App\Controller\UsersController
  action: logout

set_like:
  method: 'post'
  path: 'setlike'
  controller: App\Controller\HomeController
  action: setlike

